{
    "fix": "https://android.googlesource.com/platform/external/perfetto//+/6b89433d4ad1808b386659f3afe491b19bb0acf6%5E%21/",
    "verify": "0",
    "localId": 13724,
    "project": "perfetto",
    "fuzzer": "libfuzzer",
    "sanitizer": "asan",
    "crash_type": "UNKNOWN READ",
    "report": {
        "comments": [
            {
                "projectName": "oss-fuzz",
                "localId": 13724,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1552574180,
                "content": "Detailed report: https://oss-fuzz.com/testcase?key=5740416861732864\n\nProject: perfetto\nFuzzer: libFuzzer_perfetto_trace_processor_fuzzer\nFuzz target binary: trace_processor_fuzzer\nJob Type: libfuzzer_asan_perfetto\nPlatform Id: linux\n\nCrash Type: UNKNOWN READ\nCrash Address: 0x6310000ed9f8\nCrash State:\n  perfetto::trace_processor::ProtoTraceParser::ParseTypedFtraceToRaw\n  perfetto::trace_processor::ProtoTraceParser::ParseFtracePacket\n  perfetto::trace_processor::TraceSorter::SortAndExtractEventsBeyondWindow\n  \nSanitizer: address (ASAN)\n\nRegressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_perfetto&range=201902220355:201902230358\n\nReproducer Testcase: https://oss-fuzz.com/download?testcase_id=5740416861732864\n\nIssue filed automatically.\n\nSee https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md for instructions to reproduce this bug locally.\n\nThis bug is subject to a 90 day disclosure deadline. If 90 days elapse\nwithout an upstream patch, then the bug report will automatically\nbecome visible to the public.\n\nWhen you fix this bug, please\n  * mention the fix revision(s).\n  * state whether the bug was a short-lived regression or an old bug in any stable releases.\n  * add any other useful information.\nThis information can help downstream consumers.\n\nIf you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues.",
                "descriptionNum": 1
            },
            {
                "projectName": "oss-fuzz",
                "localId": 13724,
                "sequenceNum": 1,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1552575034,
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "OS-Linux"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 13724,
                "sequenceNum": 2,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1552782915,
                "content": "This crash occurs very frequently on linux platform and is likely preventing the fuzzer trace_processor_fuzzer from making much progress. Fixing this will allow more bugs to be found.\n\nIf this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new",
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "Fuzz-Blocker"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 13724,
                "sequenceNum": 3,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1553004577,
                "content": "ClusterFuzz has detected this issue as fixed in range 201903180235:201903190238.\n\nDetailed report: https://oss-fuzz.com/testcase?key=5740416861732864\n\nProject: perfetto\nFuzzer: libFuzzer_perfetto_trace_processor_fuzzer\nFuzz target binary: trace_processor_fuzzer\nJob Type: libfuzzer_asan_perfetto\nPlatform Id: linux\n\nCrash Type: UNKNOWN READ\nCrash Address: 0x6310000ed9f8\nCrash State:\n  perfetto::trace_processor::ProtoTraceParser::ParseTypedFtraceToRaw\n  perfetto::trace_processor::ProtoTraceParser::ParseFtracePacket\n  perfetto::trace_processor::TraceSorter::SortAndExtractEventsBeyondWindow\n  \nSanitizer: address (ASAN)\n\nRegressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_perfetto&range=201902220355:201902230358\nFixed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_perfetto&range=201903180235:201903190238\n\nReproducer Testcase: https://oss-fuzz.com/download?testcase_id=5740416861732864\n\nSee https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md for instructions to reproduce this bug locally.\n\nIf you suspect that the result above is incorrect, try re-doing that job on the test case report page."
            },
            {
                "projectName": "oss-fuzz",
                "localId": 13724,
                "sequenceNum": 4,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1553004969,
                "content": "ClusterFuzz testcase 5740416861732864 is verified as fixed, so closing issue as verified.\n\nIf this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new",
                "amendments": [
                    {
                        "fieldName": "Status",
                        "newOrDeltaValue": "Verified",
                        "oldValue": "New"
                    },
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "ClusterFuzz-Verified"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 13724,
                "sequenceNum": 5,
                "commenter": {
                    "userId": "4164592774",
                    "displayName": "sheriffbot@chromium.org"
                },
                "timestamp": 1555601099,
                "content": "This bug has been fixed for 30 days. It has been opened to the public.\n\n- Your friendly Sheriffbot",
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "-restrict-view-commit"
                    }
                ]
            }
        ]
    },
    "fix_commit": "6b89433d4ad1808b386659f3afe491b19bb0acf6",
    "repo_addr": "https://android.googlesource.com/platform/external/perfetto/"
}