{
    "fix": "https://github.com/python/cpython/commit/45862f9f5ef5d3c9da37f35e4fe4b18618530cfa",
    "verify": "0",
    "localId": 34110,
    "project": "cpython3",
    "fuzzer": "libfuzzer",
    "sanitizer": "asan",
    "crash_type": "Heap-buffer-overflow READ 1",
    "severity": "Medium",
    "report": {
        "comments": [
            {
                "projectName": "oss-fuzz",
                "localId": 34110,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1620576724,
                "content": "Detailed Report: https://oss-fuzz.com/testcase?key=5086667372363776\n\nProject: cpython3\nFuzzing Engine: libFuzzer\nFuzz Target: fuzz_sre_compile\nJob Type: libfuzzer_asan_cpython3\nPlatform Id: linux\n\nCrash Type: Heap-buffer-overflow READ 1\nCrash Address: 0x608000021df1\nCrash State:\n  skip_to_next_entry\n  get_exception_handler\n  _PyEval_EvalFrameDefault\n  \nSanitizer: address (ASAN)\n\nRecommended Security Severity: Medium\n\nRegressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_cpython3&range=202105080611:202105090619\n\nReproducer Testcase: https://oss-fuzz.com/download?testcase_id=5086667372363776\n\nIssue filed automatically.\n\nSee https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.\nWhen you fix this bug, please\n  * mention the fix revision(s).\n  * state whether the bug was a short-lived regression or an old bug in any stable releases.\n  * add any other useful information.\nThis information can help downstream consumers.\n\nIf you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.\n\nThis bug is subject to a 90 day disclosure deadline. If 90 days elapse\nwithout an upstream patch, then the bug report will automatically\nbecome visible to the public.",
                "descriptionNum": 1
            },
            {
                "projectName": "oss-fuzz",
                "localId": 34110,
                "sequenceNum": 1,
                "commenter": {
                    "userId": "1083371212",
                    "displayName": "am...@ammaraskar.com"
                },
                "timestamp": 1620578021,
                "content": "Triaging."
            },
            {
                "projectName": "oss-fuzz",
                "localId": 34110,
                "sequenceNum": 2,
                "commenter": {
                    "userId": "1083371212",
                    "displayName": "am...@ammaraskar.com"
                },
                "timestamp": 1620578231,
                "content": "Reported by Pablo in https://bugs.python.org/issue40222"
            },
            {
                "projectName": "oss-fuzz",
                "localId": 34110,
                "sequenceNum": 3,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1620587182,
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "Disclosure-2021-08-09"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 34110,
                "sequenceNum": 4,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1620750181,
                "content": "ClusterFuzz testcase 5086667372363776 is verified as fixed in https://oss-fuzz.com/revisions?job=libfuzzer_asan_cpython3&range=202105100610:202105110617\n\nIf this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new",
                "amendments": [
                    {
                        "fieldName": "Status",
                        "newOrDeltaValue": "Verified",
                        "oldValue": "New"
                    },
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "ClusterFuzz-Verified"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 34110,
                "sequenceNum": 5,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1620759491,
                "content": "This bug has been fixed. It has been opened to the public.\n\n- Your friendly Sheriffbot",
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "-restrict-view-commit"
                    }
                ]
            }
        ]
    },
    "fix_commit": "45862f9f5ef5d3c9da37f35e4fe4b18618530cfa",
    "repo_addr": "https://github.com/python/cpython.git"
}