{
    "fix": "https://github.com/guidovranken/python-library-fuzzers/commit/e977ff7fa5f8aec8529e2e0ea2e49fb5c4b93d94",
    "verify": "0",
    "localId": 58201,
    "project": "python-library-fuzzers",
    "fuzzer": "libfuzzer",
    "sanitizer": "asan",
    "crash_type": "Heap-buffer-overflow READ 1",
    "severity": "Medium",
    "report": {
        "comments": [
            {
                "projectName": "oss-fuzz",
                "localId": 58201,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1682002637,
                "content": "Detailed Report: https://oss-fuzz.com/testcase?key=4689256290582528\n\nProject: python3-libraries\nFuzzing Engine: libFuzzer\nFuzz Target: fuzzer-ast\nJob Type: libfuzzer_asan_python3-libraries\nPlatform Id: linux\n\nCrash Type: Heap-buffer-overflow READ 1\nCrash Address: 0x6020000040b2\nCrash State:\n  unicode_decode_utf8\n  PyUnicode_DecodeUTF8\n  _PyPegen_formatted_value\n  \nSanitizer: address (ASAN)\n\nRecommended Security Severity: Medium\n\nRegressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_python3-libraries&range=202304180604:202304200604\n\nReproducer Testcase: https://oss-fuzz.com/download?testcase_id=4689256290582528\n\nIssue filed automatically.\n\nSee https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.\nWhen you fix this bug, please\n  * mention the fix revision(s).\n  * state whether the bug was a short-lived regression or an old bug in any stable releases.\n  * add any other useful information.\nThis information can help downstream consumers.\n\nIf you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.\n\nThis bug is subject to a 90 day disclosure deadline. If 90 days elapse\nwithout an upstream patch, then the bug report will automatically\nbecome visible to the public.",
                "descriptionNum": 1
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58201,
                "sequenceNum": 1,
                "commenter": {
                    "userId": "2408361860",
                    "displayName": "guido...@gmail.com"
                },
                "timestamp": 1682008364,
                "content": "Minimal reproducer:\n\nimport ast\nast.parse(bytes([0x66, 0x27, 0x7b, 0x5f, 0x3d, 0x7d, 0x7b, 0x3b]))\n\nI've reported this to security@python.org"
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58201,
                "sequenceNum": 2,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1682027188,
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "Disclosure-2023-07-19"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58201,
                "sequenceNum": 3,
                "commenter": {
                    "userId": "2408361860",
                    "displayName": "guido...@gmail.com"
                },
                "timestamp": 1682033069,
                "content": "Reported here: https://github.com/python/cpython/issues/103656"
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58201,
                "sequenceNum": 4,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1682616508,
                "content": "ClusterFuzz testcase 4689256290582528 is verified as fixed in https://oss-fuzz.com/revisions?job=libfuzzer_asan_python3-libraries&range=202304250618:202304270617\n\nIf this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new",
                "amendments": [
                    {
                        "fieldName": "Status",
                        "newOrDeltaValue": "Verified",
                        "oldValue": "New"
                    },
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "ClusterFuzz-Verified"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 58201,
                "sequenceNum": 5,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1682621406,
                "content": "This bug has been fixed. It has been opened to the public.\n\n- Your friendly Sheriffbot",
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "-restrict-view-commit"
                    }
                ]
            }
        ]
    },
    "fix_commit": "e977ff7fa5f8aec8529e2e0ea2e49fb5c4b93d94",
    "repo_addr": "https://github.com/guidovranken/python-library-fuzzers.git"
}