{
    "fix": "https://github.com/python/cpython/commit/3107b453bcceb0e2d2590fef3612859f2f802d72",
    "verify": "0",
    "localId": 61721,
    "project": "cpython3",
    "fuzzer": "libfuzzer",
    "sanitizer": "msan",
    "crash_type": "Use-of-uninitialized-value",
    "severity": "Medium",
    "report": {
        "comments": [
            {
                "projectName": "oss-fuzz",
                "localId": 61721,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1692814498,
                "content": "Detailed Report: https://oss-fuzz.com/testcase?key=5086904889245696\n\nProject: cpython3\nFuzzing Engine: libFuzzer\nFuzz Target: fuzz_sre_match\nJob Type: libfuzzer_msan_cpython3\nPlatform Id: linux\n\nCrash Type: Use-of-uninitialized-value\nCrash Address: \nCrash State:\n  _PyFunction_FromConstructor\n  PyEval_EvalCode\n  exec_code_in_module\n  \nSanitizer: memory (MSAN)\n\nRecommended Security Severity: Medium\n\nRegressed: https://oss-fuzz.com/revisions?job=libfuzzer_msan_cpython3&range=202308220602:202308230613\n\nReproducer Testcase: https://oss-fuzz.com/download?testcase_id=5086904889245696\n\nIssue filed automatically.\n\nSee https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.\nWhen you fix this bug, please\n  * mention the fix revision(s).\n  * state whether the bug was a short-lived regression or an old bug in any stable releases.\n  * add any other useful information.\nThis information can help downstream consumers.\n\nIf you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.\n\nThis bug is subject to a 90 day disclosure deadline. If 90 days elapse\nwithout an upstream patch, then the bug report will automatically\nbecome visible to the public.",
                "descriptionNum": 1
            },
            {
                "projectName": "oss-fuzz",
                "localId": 61721,
                "sequenceNum": 1,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1692816991,
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "Disclosure-2023-11-21"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 61721,
                "sequenceNum": 2,
                "commenter": {
                    "userId": "388504672",
                    "displayName": "alex....@gmail.com"
                },
                "timestamp": 1692826912,
                "content": "https://github.com/python/cpython/pull/108296#issuecomment-1690683228 is the regressor, I have left a comment"
            },
            {
                "projectName": "oss-fuzz",
                "localId": 61721,
                "sequenceNum": 3,
                "commenter": {
                    "userId": "382749006",
                    "displayName": "ClusterFuzz-External"
                },
                "timestamp": 1692894129,
                "content": "ClusterFuzz testcase 5086904889245696 is verified as fixed in https://oss-fuzz.com/revisions?job=libfuzzer_msan_cpython3&range=202308230613:202308240620\n\nIf this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new",
                "amendments": [
                    {
                        "fieldName": "Status",
                        "newOrDeltaValue": "Verified",
                        "oldValue": "New"
                    },
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "ClusterFuzz-Verified"
                    }
                ]
            },
            {
                "projectName": "oss-fuzz",
                "localId": 61721,
                "sequenceNum": 4,
                "commenter": {
                    "userId": "1950284618",
                    "displayName": "sheriffbot"
                },
                "timestamp": 1692902946,
                "content": "This bug has been fixed. It has been opened to the public.\n\n- Your friendly Sheriffbot",
                "amendments": [
                    {
                        "fieldName": "Labels",
                        "newOrDeltaValue": "-restrict-view-commit"
                    }
                ]
            }
        ]
    },
    "fix_commit": "3107b453bcceb0e2d2590fef3612859f2f802d72",
    "repo_addr": "https://github.com/python/cpython.git"
}